CREATE TABLE IF NOT EXISTS participant_data (
 id SERIAL PRIMARY KEY,
 nama VARCHAR(50) NOT NULL,
 nim DOUBLE PRECISION NOT NULL,
 email VARCHAR(50) NOT NULL,
 nomor_telepon VARCHAR(50) NOT NULL,
 id_line VARCHAR(50) NOT NULL,
 jurusan VARCHAR(50) NOT NULL,
 fakultas VARCHAR(50) NOT NULL,
 angkatan VARCHAR(50) NOT NULL,
 nomor_kursi SERIAL
);

CREATE TABLE IF NOT EXISTS student_data (
 id SERIAL PRIMARY KEY,
 nama VARCHAR(50) NOT NULL,
 nim DOUBLE PRECISION NOT NULL
);